export const RULES = {
    tickRate: 30,
    roundTimeSeconds: 300,
    halfTimeSeconds: 300,
    suddenDeathSeconds: 120,
    halfScoreCap: 4,
    matchScoreCap: 8,
    cipherKeysToDestroyObjective: 2,
    nodeOverloadCooldownSeconds: 45,
    countdownTimeSeconds: 5,
    preliveTimeSeconds: 10,
    postmatchTransitionSeconds: 5,
    postmatchTimeSeconds: 20,
    postmatchPedestalRecheckSeconds: 1,
    postmatchPedestalToleranceMeters: 0.5,
    redeployTimeSeconds: 5,
    objectiveInteractHoldSeconds: 4.5,
    objectiveArmedDestroySeconds: 45,
    bombReturnToBaseSeconds: 30,
    timerLanes: {
        phaseSecondMs: 1000,
        liveFastMs: 100,
        liveSlowMs: 300,
        endgameAudioMs: 500,
        damageZonePulseMs: 250,
        iconFollowMs: 50,
        holdUiMs: 50,
        noFireEnforceMs: 1000,
    },
} as const;
