export const RULES = {
    tickRate: 30,
    roundTimeSeconds: 300,
    halfTimeSeconds: 300,
    suddenDeathSeconds: 120,
    halfScoreCap: 4,
    matchScoreCap: 8,
    cipherKeysToDestroyObjective: 2,
    countdownTimeSeconds: 5,
    preliveTimeSeconds: 15,
    postmatchTimeSeconds: 20,
    redeployTimeSeconds: 0,
    objectiveInteractHoldSeconds: 4.5,
    objectiveArmedDestroySeconds: 45,
    bombReturnToBaseSeconds: 30,
    timerLanes: {
        disabledMcomEnforceMs: 500,
        phaseSecondMs: 1000,
        liveFastMs: 100,
        liveSlowMs: 300,
        endgameAudioMs: 500,
        damageZonePulseMs: 250,
        iconFollowMs: 50,
        holdUiMs: 50,
        noFireEnforceMs: 1000,
    },
} as const;
